sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9 BOOST_VERSION=1.61.0
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5 BOOST_VERSION=1.61.0
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=clang++ BOOST_VERSION=1.61.0
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env: COMPILER=g++-6 TEST_HANA=true BOOST_VERSION=1.61.0

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq gdb libboost-dev

install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR}

  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - if [[ "${BOOST_VERSION}" == "default" ]]; then BOOST_VERSION=1.60.0; fi;

  - if [[ ! -d ${DEPS_DIR}/boost ]]; then
      mkdir -p ${DEPS_DIR} && cd ${DEPS_DIR};

      if [[ "${BOOST_VERSION}" == "1.60.0" ]]; then BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.60.0/boost_1_60_0.tar.gz"; fi;
      if [[ "${BOOST_VERSION}" == "1.61.0" ]]; then BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz"; fi;
      if [[ "${BOOST_URL}" != "" ]]; then mkdir boost && travis_retry wget -O - ${BOOST_URL} | tar --strip-components=1 -xz -C boost; fi;
      cd boost/tools/build && ./bootstrap.sh && ./b2 install --prefix=${DEPS_DIR}/b2;
      cd ${TRAVIS_BUILD_DIR};
    fi
  - export PATH=${DEPS_DIR}/b2/bin:${PATH}
  - export BOOST_ROOT=${DEPS_DIR}/boost 
  - cd ${DEPS_DIR}/boost
  - pwd
  - ls
  - ls boost/mpl/range_c.hpp
  - cd ${TRAVIS_BUILD_DIR}
  - pwd
  - ls
script:
  - echo ${COMPILER}
  - echo ${CXX}
  - $CXX --version
  - |-
    JAM="using clang : : ${CXX} ;"

  - touch project-config.jam
  - echo "${JAM}" > project-config.jam

  - echo "With Boost ${BOOST_VERSION}"
- ./test.sh --toolset=clang